### ISSUE TITLE
update-user : The OData request is not supported

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#231]
# Repro
```PowerShell
connect-graph -Scopes @("User.ReadWrite.All", "MailboxSettings.ReadWrite")
update-user -userId $Id -MailboxSettings @{"timeZone"="Eastern Standard Time"}
```
# Error
update-user : The OData request is not supported

# Intent
PATCH https://graph.microsoft.com/beta/users/id/mailboxSettings
```JSON
{
"timeZone": "Eastern Standard Time"
}
```
# Environment information
PS 5.1.18362.145
Windows 10 1903 18362.476
Microsoft.Graph.Beta 0.1.3
 
[AB#7451](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7451)

**Comment by baywet** [comment]
@peombwa Here is another of my "prior to joining the team" issue. I believe the projection in the conversion library has been fixed now, could you validate please?

**Comment by peombwa** [comment]
This is still not fixed. We don't have a path for `PATCH v1.0/me/mailboxSettings` in the OpenAPI document - https://learn.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=http#request.

`MailboxSettings` is defined as a property instead of an updatable nav property.
![image](https://user-images.githubusercontent.com/7061532/215628012-acdac637-6eab-4aed-bf9a-03b694b5d7c2.png)

**Comment by baywet** [comment]
Thanks for circling back on this.
Nav prop vs prop: I believe this is because MailboxSettings is a ComplexType and not an entity type.
Not being expanded in the conversion: I believe the conversion lib has that capability now, but the setting is disabled because it'd significantly grow our descriptions.
Maybe what needs to be introduced is a new annotation to selectively expand some properties?
But since that issue was created by me prior to joining the team, and it's not linked to any customer demand, we can simply close it?

**Comment by peombwa** [comment]
Closing as fixed - https://learn.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=powershell#request.
